### PR TITLE
Ops 204 check licence based on type (private/public)

### PR DESCRIPTION
**Pull request by alourie**
# Description

Update licence checker to support validation of a specific licence type

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
- [X] I have performed a self review of my own code (including checking issues raised when creating the PR).
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
~- [ ] I have handled all new warnings generated by the compiler or IDE.~
- [X] I have rebased onto the target branch (usually main).

### CODE REVIEW

**Comment by ryanjcoleman** [comment]
Task linked: [OPS-204 Update licence-checker to validate specific licence types (private, public)](https://app.clickup.com/t/6929263/OPS-204)

**Comment by kgreav** [comment]
Looks sensible, however @alourie does this require workflow updates? Or does the action get updated to detect the public/private status of the repo?

**Comment by alourie** [comment]
> Looks sensible, however @alourie does this require workflow updates? Or does the action get updated to detect the public/private status of the repo?

I will update the action to get the parameter (for overwriting) and automatically detect the repo type. I will also update it to fetch newer version of this binary, as now it will use one from cache.

Then I will also update the workflows and the defaults.

**Review by kgreav — APPROVED** [review]
Alright, looks good - I suppose don't do the upload release until you've done those parts? Just wary of interfering with releasing that's ongoing at the moment.

**Pull request merged**
