### PR TITLE
EWB-1879: Add closed source template

### PR DESCRIPTION
**Pull request by Lax125**
# Description

Adds Zepben's closed source license to the list of accepted licenses in the checker. See https://app.clickup.com/t/6929263/EWB-1879 for detailed information.

# Associated tasks:

This is a subtask of https://app.clickup.com/t/6929263/EWB-1003.

# Checklist:

- [x] I have performed a self review of my own code.
- [x] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [x] I have updated any documentation required for these changes.
- [x] I have handled all new warnings generated by the compiler or IDE.

### CODE REVIEW

**Comment by Lax125** [comment]
Added a simple test to ensure that the closed source license is recognized in both C-style multiline and shell-style comments. I also added a test step in the action.

**Comment by Lax125** [comment]
Are we using the spelling licen***c***e or licen***s***e for the noun? I saw some inconsistency in the code/documentation

**Review by kgreav — APPROVED** [review]

**Review by kgreav — CHANGES_REQUESTED** [review]
I've added a build workflow so the test runs on the PR - can you check why the build/test is failing?

**Comment by Lax125** [comment]
That was the fallout of me attempting to fix the spelling to licen*c*e for everything except google's library, clearly I overlooked that. I'll make sure it builds locally before pushing again

**Review by kgreav — APPROVED** [review]

**Comment by kgreav** [comment]
Thanks Marcus - great work.

**Pull request merged**
